"""Generate an MCP gateway mapping file from a live upstream's tool catalog.

    agentplane mcp discover --upstream https://mcp.example.com/mcp \
        --tenant acme --agent repo-agent --task cleanup --lease lease-cleanup \
        --out config/mcp-gateway.yaml

Discovery lists the upstream's tools and emits one operator mapping per tool
with the upstream input schema tightened to ``additionalProperties: false``,
an action of ``<prefix>.<tool>``, and a resource template that uses the first
required string argument (``{arg}``) or the literal tool name. The output is a
starting point to review, not a policy: check every ``action`` and
``resource`` before enabling the gateway, and drop tools you never want
reachable. Mappings whose schema cannot be made gateway-safe (non-object,
``$ref``) are written commented-out with the reason.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
from pathlib import Path
from typing import Any

import yaml

_NAME = re.compile(r"[^a-zA-Z0-9_.-]")


def _sanitize(name: str) -> str:
    cleaned = _NAME.sub("_", name)[:100]
    return cleaned or "tool"


def _first_string_arg(schema: dict[str, Any]) -> str | None:
    props = schema.get("properties") or {}
    required = schema.get("required") or []
    for key in (*required, *props):
        spec = props.get(key) or {}
        if spec.get("type") == "string" and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            return key
    return None


def mapping_for(tool_name: str, schema: dict[str, Any] | None, description: str | None,
                *, prefix: str, resource_prefix: str) -> tuple[dict[str, Any] | None, str | None]:
    """Return (mapping, reason). ``mapping`` is None when it cannot be made safe."""
    schema = dict(schema or {"type": "object", "properties": {}})
    if schema.get("type") != "object":
        return None, "input schema is not an object"
    if any(f'"{k}"' in json.dumps(schema) for k in ("$ref", "$dynamicRef")):
        return None, "schema uses $ref, which the gateway does not resolve"
    schema["additionalProperties"] = False
    schema.setdefault("properties", {})
    public = _sanitize(f"{prefix}.{tool_name}" if prefix else tool_name)
    arg = _first_string_arg(schema)
    resource = f"{resource_prefix}/{{{arg}}}" if arg else f"{resource_prefix}/{_sanitize(tool_name)}"
    return {
        "name": public,
        "upstream_tool": tool_name,
        "action": public,
        "resource": resource,
        "description": (description or "Governed tool; permission is checked for each call.")[:200],
        "input_schema": schema,
    }, None


async def _list_upstream(url: str, secret_env: str | None, timeout: float) -> list[Any]:
    import httpx2
    from mcp import Client
    from mcp.client.streamable_http import streamable_http_client

    from agent_plane.gateway.mcp import PROTOCOL

    headers = {"Accept-Encoding": "identity"}
    if secret_env:
        headers["Authorization"] = "Bearer " + os.environ[secret_env]
    tools: list[Any] = []
    async with httpx2.AsyncClient(headers=headers, timeout=timeout, trust_env=False) as http:
        async with Client(streamable_http_client(url, http_client=http), mode=PROTOCOL, cache=None) as client:
            cursor = None
            for _ in range(10):
                page = await client.list_tools(cursor=cursor)
                tools.extend(page.tools)
                cursor = page.next_cursor
                if not cursor:
                    break
    return tools


def render(tools: list[Any], *, upstream_url: str, secret_env: str | None, tenant: str,
           agent: str, task: str, lease: str, prefix: str, resource_prefix: str) -> str:
    mappings: list[dict[str, Any]] = []
    skipped: list[tuple[str, str]] = []
    for tool in tools:
        schema = getattr(tool, "input_schema", None) or getattr(tool, "inputSchema", None)
        mapping, reason = mapping_for(tool.name, schema, getattr(tool, "description", None),
                                      prefix=prefix, resource_prefix=resource_prefix)
        if mapping is None:
            skipped.append((tool.name, reason or "unsupported"))
        else:
            mappings.append(mapping)
    doc = {
        "upstream_url": upstream_url,
        **({"upstream_secret_env": secret_env} if secret_env else {}),
        "timeout_seconds": 10,
        "max_concurrency": 8,
        "bindings": [{"tenant": tenant, "agent": agent, "task": task, "lease": lease}],
        "tools": mappings,
    }
    header = [
        "# Generated by `agentplane mcp discover`. REVIEW BEFORE USE.",
        "# - Every `action` must appear in the bound lease's `actions` to be callable.",
        "# - `resource` templates decide what the lease's resources/protected_resources match.",
        "# - Delete mappings for tools the agent must never reach; unmapped tools are unreachable.",
        f"# Upstream tools discovered: {len(tools)}; mapped: {len(mappings)}; skipped: {len(skipped)}.",
    ]
    for name, reason in skipped:
        header.append(f"#   skipped {name}: {reason}")
    body = yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)
    return "\n".join(header) + "\n" + body


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="agentplane mcp", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    disc = sub.add_parser("discover", help="emit a gateway mapping file from an upstream's tool list")
    disc.add_argument("--upstream", required=True, help="upstream MCP URL (Streamable HTTP)")
    disc.add_argument("--secret-env", help="env var holding the upstream bearer token")
    disc.add_argument("--tenant", required=True)
    disc.add_argument("--agent", required=True)
    disc.add_argument("--task", required=True)
    disc.add_argument("--lease", required=True, help="lease id that binds this agent+task")
    disc.add_argument("--prefix", default="", help="public tool/action prefix, e.g. 'repo'")
    disc.add_argument("--resource-prefix", default="mcp", help="resource template prefix")
    disc.add_argument("--timeout", type=float, default=10.0)
    disc.add_argument("--out", type=Path, help="write YAML here (default: stdout)")
    args = parser.parse_args(argv)

    if args.cmd == "discover":
        if args.secret_env and not os.environ.get(args.secret_env):
            parser.error(f"{args.secret_env} is not set in the environment")
        tools = asyncio.run(_list_upstream(args.upstream, args.secret_env, args.timeout))
        text = render(tools, upstream_url=args.upstream, secret_env=args.secret_env,
                      tenant=args.tenant, agent=args.agent, task=args.task, lease=args.lease,
                      prefix=args.prefix, resource_prefix=args.resource_prefix)
        if args.out:
            args.out.parent.mkdir(parents=True, exist_ok=True)
            args.out.write_text(text, encoding="utf-8")
            print(f"wrote {args.out} ({len(tools)} upstream tools)")
        else:
            print(text, end="")


if __name__ == "__main__":
    main()
